export const getFeedPosts = async () => [
  { key: '1', text: 'Card 1' },
  { key: '2', text: 'Card 2' },
  { key: '3', text: 'Card 3' },
  { key: '4', text: 'Card 4' },
  { key: '5', text: 'Card 5' },
  { key: '6', text: 'Card 6' },
  { key: '7', text: 'Card 7' },
  { key: '8', text: 'Card 8' },
  { key: '9', text: 'Card 9' },
  { key: '10', text: 'Card 10' },
  { key: '11', text: 'Card 11' },
  { key: '12', text: 'Card 11' },
  { key: '13', text: 'Card 11' },
  { key: '14', text: 'Card 11' },
  { key: '15', text: 'Card 11' },
  { key: '16', text: 'Card 11' },
  { key: '17', text: 'Card 11' },
  { key: '18', text: 'Card 11' },
  { key: '19', text: 'Card 11' },
  { key: '20', text: 'Card 11' }
];
