export const GET_EXERCISES = 'GET_EXERCISES';
export type GET_EXERCISES = typeof GET_EXERCISES;

export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export type GET_EXERCISES_SUCCESS = typeof GET_EXERCISES_SUCCESS;

export const GET_EXERCISES_FAILURE = 'GET_EXERCISES_FAILURE';
export type GET_EXERCISES_FAILURE = typeof GET_EXERCISES_FAILURE;

export const GET_EXERCISE_BY_ID = 'GET_EXERCISE_BY_ID';
export type GET_EXERCISE_BY_ID = typeof GET_EXERCISE_BY_ID;

export const GET_EXERCISE_BY_ID_SUCCESS = 'GET_EXERCISE_BY_ID_SUCCESS';
export type GET_EXERCISE_BY_ID_SUCCESS = typeof GET_EXERCISE_BY_ID_SUCCESS;

export const GET_EXERCISE_BY_ID_FAILURE = 'GET_EXERCISE_BY_ID_FAILURE';
export type GET_EXERCISE_BY_ID_FAILURE = typeof GET_EXERCISE_BY_ID_FAILURE;

export const SAVE_EXERCISE = 'SAVE_EXERCISE';
export type SAVE_EXERCISE = typeof SAVE_EXERCISE;

export const SAVE_EXERCISE_SUCCESS = 'SAVE_EXERCISE_SUCCESS';
export type SAVE_EXERCISE_SUCCESS = typeof SAVE_EXERCISE_SUCCESS;

export const SAVE_EXERCISE_FAILURE = 'SAVE_EXERCISE_FAILURE';
export type SAVE_EXERCISE_FAILURE = typeof SAVE_EXERCISE_FAILURE;

export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export type DELETE_EXERCISE = typeof DELETE_EXERCISE;

export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS';
export type DELETE_EXERCISE_SUCCESS = typeof DELETE_EXERCISE_SUCCESS;

export const DELETE_EXERCISE_FAILURE = 'DELETE_EXERCISE_FAILURE';
export type DELETE_EXERCISE_FAILURE = typeof DELETE_EXERCISE_FAILURE;
