export const GET_WORKOUTS = 'GET_WORKOUTS';
export type GET_WORKOUTS = typeof GET_WORKOUTS;

export const GET_WORKOUTS_SUCCESS = 'GET_WORKOUTS_SUCCESS';
export type GET_WORKOUTS_SUCCESS = typeof GET_WORKOUTS_SUCCESS;

export const GET_WORKOUTS_FAILURE = 'GET_WORKOUTS_FAILURE';
export type GET_WORKOUTS_FAILURE = typeof GET_WORKOUTS_FAILURE;

export const GET_WORKOUT_BY_ID = 'GET_WORKOUT_BY_ID';
export type GET_WORKOUT_BY_ID = typeof GET_WORKOUT_BY_ID;

export const GET_WORKOUT_BY_ID_SUCCESS = 'GET_WORKOUT_BY_ID_SUCCESS';
export type GET_WORKOUT_BY_ID_SUCCESS = typeof GET_WORKOUT_BY_ID_SUCCESS;

export const GET_WORKOUT_BY_ID_FAILURE = 'GET_WORKOUT_BY_ID_FAILURE';
export type GET_WORKOUT_BY_ID_FAILURE = typeof GET_WORKOUT_BY_ID_FAILURE;

export const SAVE_WORKOUT = 'SAVE_WORKOUT';
export type SAVE_WORKOUT = typeof SAVE_WORKOUT;

export const SAVE_WORKOUT_SUCCESS = 'SAVE_WORKOUT_SUCCESS';
export type SAVE_WORKOUT_SUCCESS = typeof SAVE_WORKOUT_SUCCESS;

export const SAVE_WORKOUT_FAILURE = 'SAVE_WORKOUT_FAILURE';
export type SAVE_WORKOUT_FAILURE = typeof SAVE_WORKOUT_FAILURE;

export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export type DELETE_WORKOUT = typeof DELETE_WORKOUT;

export const DELETE_WORKOUT_SUCCESS = 'DELETE_WORKOUT_SUCCESS';
export type DELETE_WORKOUT_SUCCESS = typeof DELETE_WORKOUT_SUCCESS;

export const DELETE_WORKOUT_FAILURE = 'DELETE_WORKOUT_FAILURE';
export type DELETE_WORKOUT_FAILURE = typeof DELETE_WORKOUT_FAILURE;
